### ISSUE TITLE
Missing ammo if no ammo used in first high slot

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#10]
If the first high slot of a ship does not have a weapon fitted using any ammo, all other fitted weapons using ammo are regarded as empty, even if they were not at the time of the kill.
Example: First high slot is a neutralizer, the missiles in the other launcher are disregarded (http://kb.bunkerhub.de/?a=kill_detail&kll_id=320900)

Example: First high slot is a launcer, ammo is recognized correctly (http://kb.bunkerhub.de/?a=kill_detail&kll_id=320829)

The problem seems to be in the Statistics::slot() method, which looks for ammo explicitly in the first High or medium power slot (disregarding charges for ancillary armor reppers in the low slots).

**Comment by chrissheppard41** [comment]
http://sc-cdn.scaleengine.net/i/26a051b1e0b2e501240824c3570bdafa.png

Works for me unfortunately
