### ISSUE TITLE
Ammo for Rapid Heavy Missile Launchers is not recognized

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#11]
The logic for assigning missiles to launchers needs to be tweaked since the introduction of Rapid Heavy Missile Launchers. The Fitting::buildFit() method needs to be updated accordingly.
See https://github.com/evekb/evedev-kb/blob/4.0-dev/common/kill_detail.php#L1084-L1094 for a reference.

**Comment by chrissheppard41** [comment]
Added
