### ISSUE TITLE
Scan Resolution / Targeting Range Scripts imply existence of Sensor Booster

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#12]
If the mod finds Scan Resolution or Targeting Range Scripts fitted on a ship it automatically assumes there are also Sensor Boosters fitted. But if there only are Remote Sensor Boosters, it tries to access an array which is NULL, causining multiple warnings.

Add a check if there are really sensor boosters before trying to access the sensorbooster array in the Fitting class: https://github.com/chrissheppard41/ship_display_tool/blob/eve42/Libs/Fitting.class.php#L1441-L1448

Example kill CREST link: http://public-crest.eveonline.com/killmails/40926839/6ac342f9bcf6b9e6a2a05fdf6fe564fccce4243f/

**Comment by chrissheppard41** [comment]
Fixed

**Comment by Salvoxia** [comment]
Hi,

this doesn't seem fixed for me. Tested with the latest changes and this kill:
http://public-crest.eveonline.com/killmails/41169351/03f07580784943aa76c334cb6d6c0bcf03bde5b5/

Regards,
Salvoxia
