### ISSUE TITLE
Wrong reference to Statistics class

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#3]
The PHP class in Libs/Statistics.class.php is actually called "Statis_i_tics" (without the _). It is correctly referenced as such throughout the Fitting class except in lines 1643 and 1645, where it is referenced as (correctly spelled) "Statistics" and thus is not found.

Fatal error: Class 'Statistics' not found in /www/htdocs/******/killboard/mods/ship_display_tool/Libs/Fitting.class.php on line 1645

Additionally, in line 1645 parameter 5 is an Integer, which cannot be passed as reference, as expected for that parameter by the method called, leading to:
Fatal error: Cannot pass parameter 5 by reference in /www/htdocs/******/killboard/mods/ship_display_tool/Libs/Fitting.class.php on line 1645

**Comment by chrissheppard41** [comment]
Fixed
