### ISSUE TITLE
Modules from ships in SMA show for main ship

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#4]
When displaying the loss of a ship that had fitted ships in its ship maintenance bay, the modules fitted on the ships in the SMA get displayed as fitted on the main ship.

CREST link for an affected kill: http://public-crest.eveonline.com/killmails/39366844/7f1767445948b24f01dd72745f52f1ec7176ad56/

Screenshot:
![2014-06-07 20_06_51-kill details](https://cloud.githubusercontent.com/assets/6501566/3209428/91ee6294-ee6e-11e3-970a-22be1230427b.png)

**Comment by chrissheppard41** [comment]
Fixed
