### ISSUE TITLE
Division by zero in FittingTools::remoteRepStats()

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#5]
Encountered a kill throwing Division by zero errors with the following stacktrace:
WARNING [2] Division by zero
Error on line 1242 in file /www/htdocs//*****_//killboard/mods/ship_display_tool/init.php
PHP 5.2.12-nmm4 (Linux), EDK 4.2.1.0 (Kronos 1.0)
File: /www/htdocs/**_**_/killboard/mods/ship_display_tool/init.php, line: 1242, class: EDKError, function: handler
File: /www/htdocs/**_**_/killboard/mods/ship_display_tool/init.php, line: 635, class: FittingTools, function: remoteRepStats
File: /www/htdocs/**_**_/killboard/mods/ship_display_tool/init.php, line: 351, class: FittingTools, function: getExtraStats
File: /www/htdocs/**_**_/killboard/common/includes/class.pageassembly.php, line: 80, function: call_user_func_array
File: /www/htdocs/**_**_/killboard/common/includes/class.pageassembly.php, line: 44, class: pageAssembly, function: call
File: /www/htdocs/**_**_/killboard/common/kill_detail.php, line: 1620, class: pageAssembly, function: assemble
File: /www/htdocs/**_**_/killboard/common/index.php, line: 303, function: include
File: /www/htdocs/**_***/killboard/index.php, line: 27, function: include

Link to kill causing this problem: http://public-crest.eveonline.com/killmails/39436269/be5b4f7a6e8b98c3438c2e48f1e849da4695c899/

**Comment by chrissheppard41** [comment]
Fixed
