### ISSUE TITLE
Apply bugfix to EDK item list class

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#6]
There has been a bug in class.itemlist.php since the release of EDK 4.2, causing items in the "None" bay (Inventory Flag 0) to be displayed with their quantity doubled.
This bug has been fixed with commit https://github.com/evekb/evedev-kb/commit/2752cd4a4f18abb705566d5ded0606ab920c03c2 , but since the mod brings its own version of the library, this bug has been inherited and needs to be fixed there as well

**Comment by chrissheppard41** [comment]
Solved, sitting ready for the next realease
