### ISSUE TITLE
Enhancement: Support zKillboard as source

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#7]
As of EDK 4.2.2.0 fetching from zKillboard is supported. This mod in version 3.5 doesn't know zKillboard as source, so the "source" field is blank.
![2014-07-28 17_49_27-ev0ke killboard kill details](https://cloud.githubusercontent.com/assets/6501566/3722960/f6fc5592-166e-11e4-85a1-07b8e4bf1c85.png)

Enhancement: Add zKillboard as valid source, perhaps even with a link to the exact kill (see here for how to identify a kill from zKillboard and parsing the source: https://github.com/evekb/evedev-kb/blob/4.0-dev/common/kill_detail.php#L1624)

**Comment by chrissheppard41** [comment]
Ready for next release
