### ISSUE TITLE
Enhancement: Expose a kill's CREST link

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#8]
As of EDK 4.2.2.0 a kill's CREST link is exposed when not using any kill_detail mods.
To maintain this functionality, expose a kill's CREST link (perhaps as link in the source field).
The Kill class has a method called getCrestUrl(), which returns either the kills CREST link or NULL, if the kill has not been posted via CREST (see https://github.com/evekb/evedev-kb/blob/4.0-dev/common/includes/class.kill.php#L1824).

Perhaps even add "CREST" as new source type for a kill.

**Comment by chrissheppard41** [comment]
I've added in crest as a source type, I don't expose the url, I leave all that stuff to this menu: http://screencloud.net/v/q7AE
