### ISSUE TITLE
Roles Bonuses are not applied correctly

### ISSUE THREAD

**Issue by Salvoxia** [chrissheppard41/ship_display_tool#9]
Role Bonuses on ships (skillID = -1 in kb3_invtratis table) cause strange effects to be applied on the fitting stats.
Example: http://kb.bunkerhub.de/?a=kill_detail&kll_id=320826 (-4164.1 DPS).
When removing the role bonus from kb3_invtraits the DPS value returns to a more sane 973 DPS (missing the Role Bonus of 25% rate of fire).

**Comment by chrissheppard41** [comment]
Fixed, whats the new forum url

**Comment by Salvoxia** [comment]
Forum URL hasn't changed, it's still reachable under http://www.evekb.org/forum

**Comment by Salvoxia** [comment]
Hi,

it seems role bonuses still are an issue. The latest changes only work for role bonuses >25% and only for weapon rate of fire.
With the latest update we're looking at HIC role bonuses of 20% shield/armor resistances, which get multiplied by 5 in the mod, resulting in 100% all resi (and division by zero).
Example: http://kb.bunkerhub.de/?a=kill_detail&kll_id=333807

Regards,
Salvoxia
